version: '3.8'

services:
  co-organizer:
    image: co-organizer:1.0.0
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - /Users/developer/Desktop/co-organizer/:/app
    working_dir: /app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/developer/Desktop/co-organizer/postgres_data
      o: bind